title: Блог Артёма Осепяна
description: Заметки о разработке
url: "https://artengin.github.io"
baseurl: "/blog"
lang: ru
timezone: Europe/Moscow
remote_theme: "jekyll/minima@4de3223"
minima:
  skin: auto
plugins:
  - jekyll-feed
  - jekyll-remote-theme
github_username: artengin
defaults:
  - scope:
      type: posts
    values:
      layout: post
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
