title: Блог Артёма Осепяна
description: Заметки о разработке
url: "https://artengin.github.io"
baseurl: "/blog"
lang: ru
timezone: Europe/Moscow
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
github_username: artengin
defaults:
  - scope:
      type: posts
    values:
      layout: post
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
